#include "report_tab.h"
#include <QAbstractTableModel>
#include <QApplication>
#include <QClipboard>
#include <QFile>
#include <QFileDialog>
#include <QHeaderView>
#include <QLabel>
#include <QPushButton>
#include <QRegularExpression>
#include <QSaveFile>
#include <QTableView>
#include <QVBoxLayout>
#include <QColor>
#include <QFont>
#include <algorithm>
#include <stdexcept>

namespace report_format {
Rows parse(const QString& text)
{
    Rows rows;
    auto lines = text.split('\n');
    if (!lines.isEmpty() && lines.back().isEmpty()) lines.removeLast();
    const QRegularExpression separator("(?: {2,}|\\t+)");
    for (auto line : lines) {
        line = line.trimmed();
        if (rows.isEmpty() && line.startsWith(QChar(0xfeff))) line.remove(0, 1);
        rows.push_back(line.isEmpty() ? QStringList{} : line.split(separator));
    }
    if (rows.isEmpty() || rows.front().size() < 10 || rows.front()[0] != "res_time" ||
        rows.front()[8] != "profile_type")
        throw std::runtime_error("Choose a text report generated by Export report (save_excel_output).");
    for (const auto& row : rows)
        if (!row.isEmpty() && row.size() < 9)
            throw std::runtime_error("The report contains an incomplete row (fewer than nine metadata fields).");
    return rows;
}

QString tsv(const Rows& rows)
{
    QString output;
    for (const auto& row : rows) output += row.join('\t') + "\r\n";
    return output;
}
}

namespace {
class ReportModel : public QAbstractTableModel {
    report_format::Rows rows_;
    int columns_ = 0;
public:
    explicit ReportModel(const report_format::Rows& rows, QObject* parent)
        : QAbstractTableModel(parent), rows_(rows) {
        for (const auto& row : rows_) columns_ = std::max(columns_, int(row.size()));
    }
    int rowCount(const QModelIndex& parent = {}) const override { return parent.isValid() ? 0 : int(rows_.size()); }
    int columnCount(const QModelIndex& parent = {}) const override { return parent.isValid() ? 0 : columns_; }
    QVariant data(const QModelIndex& index, int role) const override {
        if (!index.isValid()) return {};
        const auto& row = rows_[index.row()];
        if (role == Qt::DisplayRole && index.column() < row.size()) return row[index.column()];
        if (!row.isEmpty() && (row[0] == "res_time" || row[0] == "sec")) {
            if (role == Qt::BackgroundRole) return QColor(row[0] == "res_time" ? "#dbeafe" : "#e2e8f0");
            if (role == Qt::ForegroundRole) return QColor("#172554");
            if (role == Qt::FontRole) { QFont font; font.setBold(true); return font; }
        }
        return {};
    }
};
}

ReportTab::ReportTab(QWidget* parent) : QWidget(parent)
{
    auto* layout = new QVBoxLayout(this);
    auto* note = new QLabel("Open an exported text report, then copy into Excel using Paste Special > Text to keep your sheet formatting. Rows, units and numeric precision are preserved.");
    note->setWordWrap(true); layout->addWidget(note);
    auto* buttons = new QHBoxLayout;
    auto* open = new QPushButton("Open report..."); open->setObjectName("openReportButton");
    copy_ = new QPushButton("Copy for Excel"); copy_->setObjectName("copyReportButton");
    save_ = new QPushButton("Save tab-separated file..."); save_->setObjectName("saveReportButton");
    buttons->addWidget(open); buttons->addWidget(copy_); buttons->addWidget(save_); buttons->addStretch();
    layout->addLayout(buttons);
    status_ = new QLabel("Open a text report or use Export report after a run.");
    status_->setObjectName("reportStatus"); status_->setTextFormat(Qt::PlainText); status_->setWordWrap(true);
    layout->addWidget(status_);
    table_ = new QTableView; table_->setObjectName("reportTable");
    table_->setAlternatingRowColors(true); table_->setWordWrap(false);
    table_->setEditTriggers(QAbstractItemView::NoEditTriggers);
    table_->horizontalHeader()->setDefaultSectionSize(150);
    layout->addWidget(table_, 1);
    copy_->setEnabled(false); save_->setEnabled(false);
    connect(open, &QPushButton::clicked, this, [this] {
        const auto name = QFileDialog::getOpenFileName(this, "Open text report", filename_, "Text reports (*.txt);;All files (*)");
        if (!name.isEmpty()) loadFile(name);
    });
    connect(copy_, &QPushButton::clicked, this, [this] {
        QApplication::clipboard()->setText(report_format::tsv(rows_));
        status_->setText("Copied all report rows for Excel: " + filename_);
    });
    connect(save_, &QPushButton::clicked, this, [this] {
        const auto name = QFileDialog::getSaveFileName(this, "Save tab-separated report", filename_ + ".tsv", "Tab-separated files (*.tsv)");
        if (name.isEmpty()) return;
        QSaveFile file(name);
        const auto bytes = report_format::tsv(rows_).toUtf8();
        if (!file.open(QIODevice::WriteOnly) || file.write(bytes) != bytes.size() || !file.commit()) {
            status_->setText("Cannot save report: " + file.errorString()); return;
        }
        status_->setText("Saved: " + name);
    });
}

bool ReportTab::loadFile(const QString& filename)
{
    rows_.clear(); copy_->setEnabled(false); save_->setEnabled(false);
    auto* old = table_->model(); table_->setModel(nullptr); delete old;
    QFile file(filename);
    if (!file.open(QIODevice::ReadOnly)) {
        status_->setText("Cannot open report: " + file.errorString()); return false;
    }
    const auto bytes = file.readAll();
    if (file.error() != QFileDevice::NoError) {
        status_->setText("Cannot read report: " + file.errorString()); return false;
    }
    try { rows_ = report_format::parse(QString::fromUtf8(bytes)); }
    catch (const std::exception& error) { status_->setText(QString::fromUtf8(error.what())); return false; }
    filename_ = filename;
    table_->setModel(new ReportModel(rows_, table_));
    table_->setColumnWidth(8, 300);
    copy_->setEnabled(true); save_->setEnabled(true);
    status_->setText(QString("%1 rows · %2").arg(rows_.size()).arg(filename));
    return true;
}
