
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/Program Files/CMake/share/cmake-3.30/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:3 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "D:/Program Files/CMake/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "D:/Program Files/CMake/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "D:/Program Files/CMake/share/cmake-3.30/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      1
      Microsoft (R) Build Engine version 14.0.25420.1
      Copyright (C) Microsoft Corporation. All rights reserved.
      
      Build started 8/30/2024 7:21:06 AM.
      Project "D:\\GitHub\\1DNavierStokes-Transient\\CMakeFiles\\3.30.2\\CompilerIdC\\CompilerIdC.vcxproj" on node 1 (default targets).
      PrepareForBuild:
        Creating directory "Debug\\".
        Creating directory "Debug\\CompilerIdC.tlog\\".
      InitializeBuildStatus:
        Creating "Debug\\CompilerIdC.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
      ClCompile:
        CL.exe /c /nologo /W0 /WX- /Od /Oy- /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc140.pdb" /Gd /TC /analyze- /errorReport:queue CMakeCCompilerId.c
      TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [D:\\GitHub\\1DNavierStokes-Transient\\CMakeFiles\\3.30.2\\CompilerIdC\\CompilerIdC.vcxproj]
        
        
      Done Building Project "D:\\GitHub\\1DNavierStokes-Transient\\CMakeFiles\\3.30.2\\CompilerIdC\\CompilerIdC.vcxproj" (default targets) -- FAILED.
      
      Build FAILED.
      
      "D:\\GitHub\\1DNavierStokes-Transient\\CMakeFiles\\3.30.2\\CompilerIdC\\CompilerIdC.vcxproj" (default target) (1) ->
      (ClCompile target) -> 
        TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [D:\\GitHub\\1DNavierStokes-Transient\\CMakeFiles\\3.30.2\\CompilerIdC\\CompilerIdC.vcxproj]
      
          0 Warning(s)
          1 Error(s)
      
      Time Elapsed 00:00:00.49
      
      
  -
    kind: "message-v1"
    backtrace:
      - "D:/Program Files/CMake/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "D:/Program Files/CMake/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "D:/Program Files/CMake/share/cmake-3.30/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      1
      Microsoft (R) Build Engine version 14.0.25420.1
      Copyright (C) Microsoft Corporation. All rights reserved.
      
      Build started 8/30/2024 7:21:07 AM.
      Project "D:\\GitHub\\1DNavierStokes-Transient\\CMakeFiles\\3.30.2\\CompilerIdC\\CompilerIdC.vcxproj" on node 1 (default targets).
      PrepareForBuild:
        Creating directory "Debug\\".
        Creating directory "Debug\\CompilerIdC.tlog\\".
      InitializeBuildStatus:
        Creating "Debug\\CompilerIdC.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
      ClCompile:
        CL.exe /c /nologo /W0 /WX- /Od /Oy- /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc140.pdb" /Gd /TC /analyze- /errorReport:queue CMakeCCompilerId.c
      TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [D:\\GitHub\\1DNavierStokes-Transient\\CMakeFiles\\3.30.2\\CompilerIdC\\CompilerIdC.vcxproj]
        
        
      Done Building Project "D:\\GitHub\\1DNavierStokes-Transient\\CMakeFiles\\3.30.2\\CompilerIdC\\CompilerIdC.vcxproj" (default targets) -- FAILED.
      
      Build FAILED.
      
      "D:\\GitHub\\1DNavierStokes-Transient\\CMakeFiles\\3.30.2\\CompilerIdC\\CompilerIdC.vcxproj" (default target) (1) ->
      (ClCompile target) -> 
        TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [D:\\GitHub\\1DNavierStokes-Transient\\CMakeFiles\\3.30.2\\CompilerIdC\\CompilerIdC.vcxproj]
      
          0 Warning(s)
          1 Error(s)
      
      Time Elapsed 00:00:00.52
      
      
  -
    kind: "message-v1"
    backtrace:
      - "D:/Program Files/CMake/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "D:/Program Files/CMake/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "D:/Program Files/CMake/share/cmake-3.30/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      1
      Microsoft (R) Build Engine version 14.0.25420.1
      Copyright (C) Microsoft Corporation. All rights reserved.
      
      Build started 8/30/2024 7:21:07 AM.
      Project "D:\\GitHub\\1DNavierStokes-Transient\\CMakeFiles\\3.30.2\\CompilerIdCXX\\CompilerIdCXX.vcxproj" on node 1 (default targets).
      PrepareForBuild:
        Creating directory "Debug\\".
        Creating directory "Debug\\CompilerIdCXX.tlog\\".
      InitializeBuildStatus:
        Creating "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
      ClCompile:
        CL.exe /c /nologo /W0 /WX- /Od /Oy- /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc140.pdb" /Gd /TP /analyze- /errorReport:queue CMakeCXXCompilerId.cpp
      TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [D:\\GitHub\\1DNavierStokes-Transient\\CMakeFiles\\3.30.2\\CompilerIdCXX\\CompilerIdCXX.vcxproj]
        
        
      Done Building Project "D:\\GitHub\\1DNavierStokes-Transient\\CMakeFiles\\3.30.2\\CompilerIdCXX\\CompilerIdCXX.vcxproj" (default targets) -- FAILED.
      
      Build FAILED.
      
      "D:\\GitHub\\1DNavierStokes-Transient\\CMakeFiles\\3.30.2\\CompilerIdCXX\\CompilerIdCXX.vcxproj" (default target) (1) ->
      (ClCompile target) -> 
        TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [D:\\GitHub\\1DNavierStokes-Transient\\CMakeFiles\\3.30.2\\CompilerIdCXX\\CompilerIdCXX.vcxproj]
      
          0 Warning(s)
          1 Error(s)
      
      Time Elapsed 00:00:00.60
      
      
  -
    kind: "message-v1"
    backtrace:
      - "D:/Program Files/CMake/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "D:/Program Files/CMake/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "D:/Program Files/CMake/share/cmake-3.30/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      1
      Microsoft (R) Build Engine version 14.0.25420.1
      Copyright (C) Microsoft Corporation. All rights reserved.
      
      Build started 8/30/2024 7:21:08 AM.
      Project "D:\\GitHub\\1DNavierStokes-Transient\\CMakeFiles\\3.30.2\\CompilerIdCXX\\CompilerIdCXX.vcxproj" on node 1 (default targets).
      PrepareForBuild:
        Creating directory "Debug\\".
        Creating directory "Debug\\CompilerIdCXX.tlog\\".
      InitializeBuildStatus:
        Creating "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
      ClCompile:
        CL.exe /c /nologo /W0 /WX- /Od /Oy- /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc140.pdb" /Gd /TP /analyze- /errorReport:queue CMakeCXXCompilerId.cpp
      TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [D:\\GitHub\\1DNavierStokes-Transient\\CMakeFiles\\3.30.2\\CompilerIdCXX\\CompilerIdCXX.vcxproj]
        
        
      Done Building Project "D:\\GitHub\\1DNavierStokes-Transient\\CMakeFiles\\3.30.2\\CompilerIdCXX\\CompilerIdCXX.vcxproj" (default targets) -- FAILED.
      
      Build FAILED.
      
      "D:\\GitHub\\1DNavierStokes-Transient\\CMakeFiles\\3.30.2\\CompilerIdCXX\\CompilerIdCXX.vcxproj" (default target) (1) ->
      (ClCompile target) -> 
        TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [D:\\GitHub\\1DNavierStokes-Transient\\CMakeFiles\\3.30.2\\CompilerIdCXX\\CompilerIdCXX.vcxproj]
      
          0 Warning(s)
          1 Error(s)
      
      Time Elapsed 00:00:00.62
      
      
...

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/Program Files/CMake/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "D:/Program Files/CMake/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "D:/Program Files/CMake/share/cmake-3.30/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      1
      Microsoft (R) Build Engine version 14.0.25420.1
      Copyright (C) Microsoft Corporation. All rights reserved.
      
      Build started 8/30/2024 7:25:21 AM.
      Project "D:\\GitHub\\1DNavierStokes-Transient\\CMakeFiles\\3.30.2\\CompilerIdC\\CompilerIdC.vcxproj" on node 1 (default targets).
      PrepareForBuild:
        Creating directory "Debug\\".
        Creating directory "Debug\\CompilerIdC.tlog\\".
      InitializeBuildStatus:
        Creating "Debug\\CompilerIdC.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
      ClCompile:
        CL.exe /c /nologo /W0 /WX- /Od /Oy- /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc140.pdb" /Gd /TC /analyze- /errorReport:queue CMakeCCompilerId.c
      TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [D:\\GitHub\\1DNavierStokes-Transient\\CMakeFiles\\3.30.2\\CompilerIdC\\CompilerIdC.vcxproj]
        
        
      Done Building Project "D:\\GitHub\\1DNavierStokes-Transient\\CMakeFiles\\3.30.2\\CompilerIdC\\CompilerIdC.vcxproj" (default targets) -- FAILED.
      
      Build FAILED.
      
      "D:\\GitHub\\1DNavierStokes-Transient\\CMakeFiles\\3.30.2\\CompilerIdC\\CompilerIdC.vcxproj" (default target) (1) ->
      (ClCompile target) -> 
        TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [D:\\GitHub\\1DNavierStokes-Transient\\CMakeFiles\\3.30.2\\CompilerIdC\\CompilerIdC.vcxproj]
      
          0 Warning(s)
          1 Error(s)
      
      Time Elapsed 00:00:00.35
      
      
  -
    kind: "message-v1"
    backtrace:
      - "D:/Program Files/CMake/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "D:/Program Files/CMake/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "D:/Program Files/CMake/share/cmake-3.30/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      1
      Microsoft (R) Build Engine version 14.0.25420.1
      Copyright (C) Microsoft Corporation. All rights reserved.
      
      Build started 8/30/2024 7:25:21 AM.
      Project "D:\\GitHub\\1DNavierStokes-Transient\\CMakeFiles\\3.30.2\\CompilerIdC\\CompilerIdC.vcxproj" on node 1 (default targets).
      PrepareForBuild:
        Creating directory "Debug\\".
        Creating directory "Debug\\CompilerIdC.tlog\\".
      InitializeBuildStatus:
        Creating "Debug\\CompilerIdC.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
      ClCompile:
        CL.exe /c /nologo /W0 /WX- /Od /Oy- /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc140.pdb" /Gd /TC /analyze- /errorReport:queue CMakeCCompilerId.c
      TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [D:\\GitHub\\1DNavierStokes-Transient\\CMakeFiles\\3.30.2\\CompilerIdC\\CompilerIdC.vcxproj]
        
        
      Done Building Project "D:\\GitHub\\1DNavierStokes-Transient\\CMakeFiles\\3.30.2\\CompilerIdC\\CompilerIdC.vcxproj" (default targets) -- FAILED.
      
      Build FAILED.
      
      "D:\\GitHub\\1DNavierStokes-Transient\\CMakeFiles\\3.30.2\\CompilerIdC\\CompilerIdC.vcxproj" (default target) (1) ->
      (ClCompile target) -> 
        TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [D:\\GitHub\\1DNavierStokes-Transient\\CMakeFiles\\3.30.2\\CompilerIdC\\CompilerIdC.vcxproj]
      
          0 Warning(s)
          1 Error(s)
      
      Time Elapsed 00:00:00.35
      
      
  -
    kind: "message-v1"
    backtrace:
      - "D:/Program Files/CMake/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "D:/Program Files/CMake/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "D:/Program Files/CMake/share/cmake-3.30/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      1
      Microsoft (R) Build Engine version 14.0.25420.1
      Copyright (C) Microsoft Corporation. All rights reserved.
      
      Build started 8/30/2024 7:25:22 AM.
      Project "D:\\GitHub\\1DNavierStokes-Transient\\CMakeFiles\\3.30.2\\CompilerIdCXX\\CompilerIdCXX.vcxproj" on node 1 (default targets).
      PrepareForBuild:
        Creating directory "Debug\\".
        Creating directory "Debug\\CompilerIdCXX.tlog\\".
      InitializeBuildStatus:
        Creating "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
      ClCompile:
        CL.exe /c /nologo /W0 /WX- /Od /Oy- /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc140.pdb" /Gd /TP /analyze- /errorReport:queue CMakeCXXCompilerId.cpp
      TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [D:\\GitHub\\1DNavierStokes-Transient\\CMakeFiles\\3.30.2\\CompilerIdCXX\\CompilerIdCXX.vcxproj]
        
        
      Done Building Project "D:\\GitHub\\1DNavierStokes-Transient\\CMakeFiles\\3.30.2\\CompilerIdCXX\\CompilerIdCXX.vcxproj" (default targets) -- FAILED.
      
      Build FAILED.
      
      "D:\\GitHub\\1DNavierStokes-Transient\\CMakeFiles\\3.30.2\\CompilerIdCXX\\CompilerIdCXX.vcxproj" (default target) (1) ->
      (ClCompile target) -> 
        TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [D:\\GitHub\\1DNavierStokes-Transient\\CMakeFiles\\3.30.2\\CompilerIdCXX\\CompilerIdCXX.vcxproj]
      
          0 Warning(s)
          1 Error(s)
      
      Time Elapsed 00:00:00.34
      
      
  -
    kind: "message-v1"
    backtrace:
      - "D:/Program Files/CMake/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "D:/Program Files/CMake/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "D:/Program Files/CMake/share/cmake-3.30/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      1
      Microsoft (R) Build Engine version 14.0.25420.1
      Copyright (C) Microsoft Corporation. All rights reserved.
      
      Build started 8/30/2024 7:25:22 AM.
      Project "D:\\GitHub\\1DNavierStokes-Transient\\CMakeFiles\\3.30.2\\CompilerIdCXX\\CompilerIdCXX.vcxproj" on node 1 (default targets).
      PrepareForBuild:
        Creating directory "Debug\\".
        Creating directory "Debug\\CompilerIdCXX.tlog\\".
      InitializeBuildStatus:
        Creating "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
      ClCompile:
        CL.exe /c /nologo /W0 /WX- /Od /Oy- /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc140.pdb" /Gd /TP /analyze- /errorReport:queue CMakeCXXCompilerId.cpp
      TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [D:\\GitHub\\1DNavierStokes-Transient\\CMakeFiles\\3.30.2\\CompilerIdCXX\\CompilerIdCXX.vcxproj]
        
        
      Done Building Project "D:\\GitHub\\1DNavierStokes-Transient\\CMakeFiles\\3.30.2\\CompilerIdCXX\\CompilerIdCXX.vcxproj" (default targets) -- FAILED.
      
      Build FAILED.
      
      "D:\\GitHub\\1DNavierStokes-Transient\\CMakeFiles\\3.30.2\\CompilerIdCXX\\CompilerIdCXX.vcxproj" (default target) (1) ->
      (ClCompile target) -> 
        TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [D:\\GitHub\\1DNavierStokes-Transient\\CMakeFiles\\3.30.2\\CompilerIdCXX\\CompilerIdCXX.vcxproj]
      
          0 Warning(s)
          1 Error(s)
      
      Time Elapsed 00:00:00.36
      
      
...
