-- Empty schema for a new 1D Navier-Stokes experiment database.
-- Keep this aligned with the tables read and written by the application.

PRAGMA foreign_keys = ON;

CREATE TABLE model_controls (
    "Parameter" TEXT NOT NULL,
    Setting ANY
);

CREATE TABLE experiments (
    NAME TEXT NOT NULL,
    LOW_REF_LEFT INT,
    LOW_REF_RIGHT INT,
    HIGH_REF_LEFT INT,
    HIGH_REF_RIGHT INT,
    PARAMETERS_TO_SOLVE_FOR TEXT,
    DEFAULT_NORMALIZATION TEXT,
    REACTIONS TEXT,
    SPECIES TEXT,
    ENTRANCE_FLOWRATE ANY,
    SPECIE_INLET_CONC_UNITS ANY,
    SPECIE_MODEL_CONC_UNITS ANY,
    EDGES,
    WIDTH NUMERIC,
    CHANNEL_WIDTH REAL NOT NULL DEFAULT 5e-4
        CHECK(typeof(CHANNEL_WIDTH) IN ('real','integer') AND CHANNEL_WIDTH > 0 AND CHANNEL_WIDTH <= 1.7976931348623157e308),
    CHANNEL_HEIGHT REAL NOT NULL DEFAULT 4e-5
        CHECK(typeof(CHANNEL_HEIGHT) IN ('real','integer') AND CHANNEL_HEIGHT > 0 AND CHANNEL_HEIGHT <= 1.7976931348623157e308),
    CHANNEL_LENGTH REAL NOT NULL DEFAULT 0.025
        CHECK(typeof(CHANNEL_LENGTH) IN ('real','integer') AND CHANNEL_LENGTH > 0 AND CHANNEL_LENGTH <= 1.7976931348623157e308),
    CONSTRAINT EXPERIMENTS_PK PRIMARY KEY (NAME)
);

CREATE TABLE species (
    SPECIES_NAME TEXT NOT NULL,
    SPECIES_TYPE TEXT,
    DIFFUSION_RATE NUMERIC,
    PARTICLE_DIAMETER NUMERIC,
    QE DOUBLE,
    PARTICLE_DENSITY DOUBLE,
    MOLECULAR_WEIGHT DOUBLE,
    CONSTRAINT species_pk PRIMARY KEY (SPECIES_NAME)
);

CREATE TABLE reactions (
    REACTION_NAME TEXT NOT NULL,
    SPECIES ANY,
    COEFFICIENTS ANY,
    Ks ANY,
    EXPONENTS ANY,
    SPECIE_UNITS
);

CREATE TABLE alglib_input (
    VARIABLE TEXT,
    "LOWER BOUND" DOUBLE,
    "UPPER BOUND" DOUBLE,
    "INITIAL VALUE" TEXT,
    "SCALE" TEXT
);

CREATE TABLE raw_profile (
    NAME TEXT NOT NULL,
    WT_PERCENT DOUBLE NOT NULL,
    CHANNEL_LEFT_EDGE INT,
    CHANNEL_RIGHT_EDGE INT,
    INTENSITY_ARRAY TEXT,
    ENTRANCE_CONC ANY,
    INLET_COND_ID INTEGER,
    OMIT ANY,
    INDEPENDENT_PARAMETERS_TO_SOLVE_FOR TEXT,
    LEFT_EDGE NUMERIC,
    WIDTH NUMERIC,
    ENTRANCE_CONC_UNITS TEXT,
    CONSTRAINT RAW_PROFILE_PK PRIMARY KEY (NAME, WT_PERCENT)
);

CREATE TABLE raw_profile_entrance_concentrations (
    NAME TEXT NOT NULL,
    WT_PERCENT TEXT NOT NULL,
    ENTRANCE_NUMBER INTEGER NOT NULL
        CHECK(typeof(ENTRANCE_NUMBER)='integer' AND ENTRANCE_NUMBER >= 1),
    SPECIES_NAME TEXT NOT NULL,
    CONCENTRATION REAL NOT NULL
        CHECK(typeof(CONCENTRATION) IN ('real','integer') AND CONCENTRATION >= 0 AND CONCENTRATION <= 1.7976931348623157e308),
    UNITS TEXT,
    PRIMARY KEY (NAME, WT_PERCENT, ENTRANCE_NUMBER, SPECIES_NAME)
);

CREATE TABLE inlet_conditions (
    INLET_COND_ID INTEGER NOT NULL,
    SPECIE_CONC NUMERIC,
    ENTRANCE_NUMBER INTEGER,
    SPECIES_NAME TEXT NOT NULL
);

CREATE TABLE solve_settings (
    SOLVE_SETTING_ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    ALL_EXP_FITTED TEXT,
    PARAMETERS_SOLVED_FOR TEXT,
    REACTIONS_ENABLED TEXT,
    SCATTER_METHOD TEXT,
    X_RESOLUTION INTEGER,
    Z_RESOLUTION INTEGER
);

CREATE TABLE solutions (
    SOLUTION_ID INTEGER NOT NULL,
    SOLVE_SETTING_ID INTEGER NOT NULL,
    EXPERIMENT_NAME TEXT NOT NULL,
    INLET_COND_ID INTEGER NOT NULL,
    EXP_DA NUMERIC,
    MODEL_DA NUMERIC,
    EXP_INTEGRAL NUMERIC,
    MODEL_INTEGRAL NUMERIC,
    SECOND_NAME TEXT,
    CONSTRAINT samples_pk PRIMARY KEY (SOLUTION_ID),
    CONSTRAINT solutions_solve_settings_FK FOREIGN KEY (SOLVE_SETTING_ID)
        REFERENCES solve_settings(SOLVE_SETTING_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE parameter_solutions (
    SOLVE_SETTING_ID INTEGER NOT NULL,
    "PARAMETER" TEXT NOT NULL,
    VALUE NUMERIC,
    UNITS TEXT,
    SOLUTION_ID INTEGER,
    "SOURCE" TEXT,
    CONSTRAINT parameter_solutions_solutions_FK FOREIGN KEY (SOLUTION_ID)
        REFERENCES solutions(SOLUTION_ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT parameter_solutions_solve_settings_FK FOREIGN KEY (SOLVE_SETTING_ID)
        REFERENCES solve_settings(SOLVE_SETTING_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE model_profile (
    SOLUTION_ID INTEGER NOT NULL,
    X NUMERIC NOT NULL,
    Free_Dye NUMERIC,
    Bound_Dye NUMERIC,
    Total_Dye NUMERIC,
    Unbound_Beads NUMERIC,
    Bound_Beads NUMERIC,
    Total_Beads NUMERIC,
    Experimental_Derivative NUMERIC,
    Numeric_Derivative NUMERIC,
    Experimental NUMERIC,
    "Numeric" NUMERIC,
    Error NUMERIC,
    Experimental_Difference NUMERIC,
    Numeric_Difference NUMERIC,
    CONSTRAINT model_profile_solutions_FK FOREIGN KEY (SOLUTION_ID)
        REFERENCES solutions(SOLUTION_ID) ON DELETE CASCADE ON UPDATE CASCADE
);
